git:
    depth: 5
branches:
    only:
      - master
language: node_js
node_js:
  - "6"
sudo: required
os:
  - linux
  - osx
osx_image: xcode8.2
dist: trusty
compiler:
  - clang
  - gcc
addons:
    apt:
        packages:
          - python
          - python-dev
          - python3
          - python3-dev
          - swig3.0
          - swig

install:
  # Brew on macOS has up to date SWIG already:
  - npm i -g node-gyp
  - cd libwally-core
  - bash -c '[ "$TRAVIS_OS_NAME" = "osx" ] || (wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz && tar -zxf swig-3.0.12.tar.gz && mkdir swig-prefix && cd swig-3.0.12 && ./configure --prefix=$PWD/../swig-prefix && make && make install)'
  - ./tools/cleanup.sh && ./tools/autogen.sh
  - PATH=$PWD/swig-prefix/bin:$PATH ./configure --enable-swig-python --enable-swig-js && make
  - cd src/swig_js
  - node-gyp configure && node-gyp build
  - npm i tape

before_install:
  - git clone https://github.com/jgriffiths/libwally-core.git -b wip_js
  - ./libwally-core/tools/travis_install.sh

script:
  - node test/test_hash.js

notifications:
    email: false
